__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)

    from .views import views
   #from .data import data 
    from .query import query
    from .webmap import webmap
    from .views import team

    app.register_blueprint(views, url_prefix='/')
   # app.register_blueprint(data, url_prefix='/')
    app.register_blueprint(query, url_prefix='/')
    app.register_blueprint(webmap, url_prefix='/')
    app.register_blueprint(team, url_prefix='/')

    return app

main.py
from recreation import create_app

app = create_app()



if __name__ == '__main__':
    app.run(host='0.0.0.0', port=55402, debug=True)

views.py
from flask import Blueprint, render_template

views = Blueprint('views', __name__)

team = Blueprint('team', __name__)

@views.route('/')
def home():
    return render_template('homepage_ARQI2.html')
    
@team.route('/aboutus')
def aboutus():
    return render_template('about_us.html')

templates/base.html
<!DOCTYPE html>

<html>
  
  <head>

    <meta charset='utf-8' />
    <!-- Dynamic rescaling of webpage to fit device size -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.8/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.8/slick-theme.min.css">
    <link rel="shortcut icon" href="static/favicon.ico">
    
    <title>{% block title %}Home{% endblock %}</title>

  </head>

  <body>

    {% block content %}
    {% endblock %}
    <footer>

      <!-- Scroll to top button -->
    <button id="btnScrollToTop">
      <i class="material-icons">arrow_upward</i>
    </button>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <!--Using JQuery to add animation to scroll to top -->
      <script>
        $(document).ready(function() {
          $("#btnScrollToTop").click(function() {
            $("html, body").animate({
              scrollTop: 0
            }, "slow");
          });
        });

      </script>

      <!-- Power carousel -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.8/slick.min.js"></script>
    <script>
      $(document).ready(function() {
        $('.carousel').slick({
          slidesToShow: 3,
          dots: true,
            centerMode: true,
	    autoplay: true,
	    autoplaySpeed: 4000,
        });
      });
    </script>
    
    </footer>
  </body>
  
</html>

templates/query_download.html
{% extends "base.html" %} {% block title %}Query and Download | Capital Greenspaces Project - Group 6{% endblock %}
{% block content %}

<!DOCTYPE html>

<html>
  <head>
    <html lang="en-GB">
    <meta charset="UTF-8">
    <title>Query and Download</title>
    <!-- Import stylesheets -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="static/webpage_style.css">

    <style>
      .about-section {
  padding:18px 80px 700px 60px;
  background-image: linear-gradient(rgba(0, 0, 0, 0.3),rgba(0, 0, 0, 0.5)), url("static/query_photo.png");
  background-position: bottom center;
  background-size:cover;
  background-repeat: no-repeat;
  color: white;
}

/* Center Image */
.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
}
      </style>
    
  </head>
 
  <body>
    <!-- Creation of interactive header-->
    <div class="header">
      <nav>
        <a href="{{ url_for('views.home') }}">Home</a>
        <a href="{{ url_for('webmap.web_map') }}">Interactive Webmap</a>
        <a class="active" href="{{ url_for('query.index') }}">Query and Download</a>
        <a href="{{ url_for('team.aboutus') }}">About Us</a>
	<a class="active" href="https://forms.office.com/r/2RnwVbTARf" target="_blank">Data Improvement</a>
      </nav>
    </div>

    <!-- Creation of About-Section Banner Image and Title -->
      <div class="about-section">
      <div class="Titletxt">
        <br><br><br><br><br><br><br><br><br><br>
        <h1><center>Dynamic Query and Data Download</center></h1>
      </div>
      </div>
    <!-- Captions over images -->
      <figure class="textover">
      <figcaption>Photo by <a href="https://unsplash.com/photos/RdE2UobZxx8?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditShareLink" alt="Photographer of image" target="_blank">Micaela Parente</a> on Unsplash</figcaption>
      </figure>
      <hr> <! -- Create thematic line break -->

    <!-- Container for dynamic query functionality -->
      <section style="background-color: #E9F5E9">
	<hr>
	<div class="w3-row-padding">
	     <h1><center><font color="#448D38">Dynamic Querying</font></center></h1><br>
	     <h3><center>Looking for data specific to a greenspace? Have a look from these drop-down menus. Simply select a greenspace and a choice of three 'services'.</center></h3>
	     <br>
	     <center>
		 <ul><b>Provision</b>: information on the presence or absence of recreational quality features</ul>
		 <ul><b>Quality</b>: information on the quality score and grade of the greenspace</ul>
		 <ul><b>Service Areas</b>: information on the datazones accessible to the selected greenspace within a 20-minutes walk</ul>
	     </center>
	     <hr>
	</div>
	
	<br>
	
   <!-- Design of HTML form (to pass data to server side) -->
<center>
<form id = "greenspaceServices" method="POST" action="{{ url_for('query.dynamic_queries') }}">
<label for="greenspace" style="font-size: 20px">Choose a greenspace:</label>
<select name="greenspace" id="greenspace">
  {% for greenspace in greenspaces %}
  <option value={{greenspace}}>{{greenspace}}</option>
  {% endfor %}
</select>
<p>
<label for="service" style="font-size: 20px">Choose a service:</label>
<select name="service" id="service" style="font-size: 18px">
  <option value="provisions">Provisions</option>
  <option value="quality">Quality</option>
  <option value="serviceAreas">Service Areas</option>
</select>
</p>
<br>
<button class="btn">Submit</button>
</form>

<!-- Design another form and button to redirect back to the mainpage (to enable infinite queries) -->
<form id="resubmit" action="{{ url_for('query.index') }}" method='POST'>
    <button class="btn" style= "width:130px">Resubmit<a href="{{url_for('query.index')}}"></button></a>
</form>

<br>
<!-- Table display design -->

<table>
  <tbody>
    <tr>
    <td>{{ query }}</td>
    </tr>
  </tbody>
  </table>
	
      </section>
      <br>
      
      
    <! -- Creation of another section -->
      <! -- Data Download -->
      <section>
      <center><h1><font color="#448D38">Data Download</font></h1></center><br>
      <center><h3>Full datasets of each of the three 'services' offered are available to be freely downloaded for your use. Available in CSV format.</h3></center> 
      <hr>
      <div class="w3-row-padding">
	  <center><img src="{{ url_for('static', filename='query_download.png') }}" alt="Download cloud" style="width:100%; height:300px;object-fit:scale-down;margin: 0px; padding: 0px;"</center>	 
      <div class="w3-third w3-container w3-margin-bottom">
	  <h3><a href="{{ url_for('static', filename='greenspaces_service_areas.csv') }}" download>Greenspace Service Areas (City of Edinburgh)</a></h3>
      </div>
      <div class="w3-third w3-container w3-margin-bottom">
	  <h3><a href="{{ url_for('static', filename='greenspace_quality.csv') }}" download>Greenspace Quality (City of Edinburgh)</a></h3>
	  <h5><i>Refer to the <a href="https://www.edinburgh.gov.uk/downloads/file/30233/parks-quality-report-2021" alt="Link to Green Flag Award Report 2021" target="_blank">Green Flag Award Report (2021)</a> for further information on greenspace grades</i></h5>
      </div>
      <div class="w3-third w3-container w3-margin-bottom">
	  <h3><a href="{{ url_for('static', filename='greenspace_provisions.csv') }}" download>Greenspace Provisions (City of Edinburgh)</a></h3>
      </div>
      </div>
      </section>
      <hr>
	     
      


<!-- Footer -->
<div class="footer_bottom_content" style="background-color:#19422A">
      <span id="footer-line" style="line-height:100px">
	<font color="#FFFFFF"><center>Design © 2021 Group 6 ARQI,<a href="https://www.ed.ac.uk/geosciences" target="_blank"> School of GeoSciences, The University of Edinburgh<br><img align="center" src="static/GeoSciences_white.png" alt="University logo" width="auto" height="85" object-fit="scale-down" /></a></center></font></span>
    
   
  </body>
  {% endblock %}
  </html>

templates/webmap.html
{% extends "base.html" %} {% block title %}Webmap | Capital Greenspaces Project - Group 6{% endblock %}
{% block content %}
<!doctype html>

<html lang="en-GB">

  <head>
    <meta charset="UTF-8">

    
    
    <title>Webmap</title>
    <!-- Import stylesheets -->
    <link rel="stylesheet" href="static/webpage_style.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="static/lightbox.css" rel="stylesheet" />
    
   
    <style>
      .about-section {
  padding:18px 80px 700px 60px;
  background-image: linear-gradient(rgba(0, 0, 0, 0.3),rgba(0, 0, 0, 0.5)), url("static/database.jpg");
  background-position: bottom center;
  background-size:cover;
  background-repeat: no-repeat;
  color: white;
}

/* Center Image */
.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
}
      </style>
    
    
  </head>

  <body>
    
    <!-- Creation of interactive header-->
    <div class="header">
      <nav>
        <a href="{{ url_for('views.home') }}">Home</a>
        <a class="active" href="{{ url_for('webmap.web_map') }}">Interactive Webmap</a>
        <a href="{{ url_for('query.index') }}">Query and Download</a>
        <a href="{{ url_for('team.aboutus') }}">About Us</a>
	<a class="active" href="static/userguide.jpg" data-lightbox="popup">User Guide</a>
      </nav>
    </div>

    <!-- Creation of About-Section Banner Image and Title -->
     <section id="webmap" align="center" >
      <div class="about-section">
      <div class="Titletxt">
        <br><br><br><br><br><br><br><br><br><br>
        <h1><center>Interactive Webmap</center></h1>
      </div>
      </div>
    <!-- Captions over images -->
      <figure class="textover">
      <figcaption>Photo by <a href="https://unsplash.com/photos/oH8G8cn52o8" alt="Photographer of image" target="_blank">Dominik Rešek</a> on Unsplash</figcaption>
      </figure>

      <hr>

      <!--DESCRIPTION-->
      <section  align="center" style="background: #E9F5E9">
	
	  

	    <!-- section title -->
	    <div class="text-center" style="background: #E9F5E9">
	      <br>
	      <center><font size="+1" color="#19422A"><p>INTERACTIVE WEBMAP</p></font>
	      <font size="+3" color="#448D38"><b>What do the map layers show?</b></font>
	      <hr>
	      <p>
		  <ul>
		    The <b><em>ARQI - Edinburgh</em></b> layer displays our index in each Datazone in Edinburgh. You can hover over the datazones to find out their score.
		  </ul>
		  <ul>
		    The <b><em>Greenspaces - Edinburgh</em></b> layer displays the greenspaces included in our study. You can hover over the greenspaces to find out their score.
		  </ul>
		  <ul>
		    The <b><em>SIMD</em></b> layer displays the Scottish Index of Multiple Deprivation. You can hover over the datazones to find out their score.
		  </ul>
		  <ul>
		    The <b><em>Greenspace Access Points</em></b> layer shows the access points of each greenspace.
		  </ul>
		  <ul>
		    The <b><em>Heatmap</em></b> layer shows where the greenspace access points are clustered in Edinburgh.
		  </ul>
		  <br>
		  <font size="+1">With the measure tool you can measure distances and areas such as the distance between a location and a greenspace access point or the area of a greenspace.<br>For visual help, please use the <em>User Guide</em> in the navigation bar on the top of the page.<br><br>
	      </font></center>
	    </div>
	  
	
	</section>
<!--WEBMAP-->
		
<div class="container">
  <div class="row">
<iframe src="https://www.geos.ed.ac.uk/~s2236682/map.html" height="900" width="100%"
        frameborder="0" scrolling="no" id="iframe">
</iframe>
  </div>
</div>

 <!--GitHub ribbon-->

<a href="https://github.com/attilacodes/Capital-Greenspaces-Project" target="_blank"><img src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" style="position: fixed; top: 0; right: 0; border: 0;" alt="Find me on GitHub" ></a>

<!--- Footer --->
      <div>
	    <hr>
	  </div>
	  <div id="footer_bottom_content" style="background-color:#19422A">
	    <div class="text-center" align="center">
          <span id="footer-line" style="line-height:100px"><font color="#FFFFFF">Design © 2021 Group 6 ARQI,<a href="https://www.ed.ac.uk/geosciences" target="_blank"> School of GeoSciences, The University of Edinburgh<br><img align="center" src="static/GeoSciences_white.png" alt="University logo" width="auto" height="85" object-fit="scale-down" /></a></font></span>
		</div>
      </div>

<script src="static/lightbox-plus-jquery.js"></script>
	  {% endblock %}
	  
</body>
</html>